spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: liquibase/db.changelog-master.yaml
feignclient:
  value: security
  url: http://security-cloud-service:8081/api/v1/user
cache:
  size: 3
  algorithm: LFU
server.port: 8080